### ISSUE TITLE
Circular color picker

### ISSUE THREAD

**Issue by Hunam6** [omgovich/react-colorful#103]
Does something like this would be possible?
![color picker](https://user-images.githubusercontent.com/38606542/104140353-75774680-53b1-11eb-8b5f-fb6d7e802308.png)

**Comment by omgovich** [comment]
Hi! **react-colorful** is a minimalist-friendly component that implements the classic color picker UI (saturation, hue, and alpha squares). Even react-color doesn't have one. I guess because developers usually don't need a circular picker. Also, I would like to mention that most of the users used to work with classic pickers, so implementing a circular one might make the UX of your project worse.

May I ask you why don't consider using a classic (square) color picker?

P.S. The only circular picker I know is https://iro.js.org/

**Comment by web-padawan** [comment]
FYI, there is a set of various color picker elements here: https://everycolorpicker.com

However, they are not as minimal as `react-colorful` (up to 6 KB gzipped) and not fully a11y compliant.
