### ISSUE TITLE
Export utils

### ISSUE THREAD

**Issue by iofjuupasli** [omgovich/react-colorful#107]
Utils from 
https://github.com/omgovich/react-colorful/blob/eebf34ab404ce946d52c67c8898f2ce3f85e5c54/src/utils/convert.ts
will be very useful for me, and I think for many other users of that library. Could you add them to exports, please?

**Comment by omgovich** [comment]
Hi! 👋 Thanks for using react-colorful.

This package is a micro React component, so exporting the utils seems like a bad idea since those functions are tuned to work inside the picker's logic, and as a consequence, the resulting values most probably won't be properly-rounded or formatted for other purposes. Also, the utils exporting makes it harder for the maintainers to avoid major releases.

I would recommend you using special packages such as [color-fns](https://github.com/swiftcarrot/color-fns).
