### ISSUE TITLE
Thoughts on exposing the common components?

### ISSUE THREAD

**Issue by hhedger-ae** [omgovich/react-colorful#137]
Exposing the base components would give more control when it comes to customization.  I also wouldn't have to override react-colorful's CSS classes just to customize the spacing/layout.

Looking at the source, it seems like the compound components are pretty straight forward.  Is there a reason to not expose those components?

**Comment by omgovich** [comment]
Hi! In my opinion, it is too difficult to create a color picker using our internal (common) components since they return values that don't describe a color: HSV saturation, HSV value, hue, and alpha. So the developer will have to write his own color conversion, formatting, and tons of logic that is already present inside of our `ColorPicker` component.

I know what I'm talking about: I tried to create a color picker component using react-color's common components and it was super difficult since I had to write a lot of code to make them as a complete color picker.

And it also much easier to customize existing styles than write them from scratch.

If a developer is able to write conversion logic and styles from scratch, I don't think he needs react-colorful at all :)
He can just use a slider component like `rc-slider` and do his own color picker. 

react-colorful aims to provide an easy-to-use solution and I don't believe that exporting internal components is a good way to help people solve their tasks. CSS customization is a powerful thing and it allows to change the picker siginificatly.

**Comment by hhedger-ae** [comment]
Thank you for taking the time to respond :) I don't want to push you on this if you aren't interested, so no worries if you don't want to discuss this further!

For context, this is what I'm building:

![image](https://user-images.githubusercontent.com/77985901/121309308-e23a3280-c8b6-11eb-93b0-6aabe515cbad.png)

The hiccup is positioning the color preview square adjacent to the hue slider.  I'm also not sure if I can reduce the height of the saturation component, but that's a different story.

Something like this would be great:

```js
<HexColorPicker>
  <Saturation className="my-custom-saturation-style" />
  <div>
    <Hue className="my-custom-hue-style" />
    <ColorPreviewSquare color={color} />
  </div>
</HexColorPicker>
```

The `HexColorPicker` could provide all the color conversion/formatting/etc, and the library could still include base CSS styles for the common components, but custom style overrides could be handled by passing classes directly to each sub-component.

Anyways, are these my options?
- Do something hacky, like position absolute the color preview into place
- Fork the library
- Get design to change the picker to conform more to react-colorful
- Something else?

Thanks again for your time. I made a donation to show my thanks!

**Comment by omgovich** [comment]
Hi! Sorry for the delay (the wedding and honeymoon stuff).

I would recommend you to customize picker styles and place the square using position absolute. That's the easiest way.

**Comment by omgovich** [comment]
Check the last example here. I guess it could help.
https://codesandbox.io/s/mq85z

**Comment by sanbornhilland** [comment]
I can appreciate the arguments you're making here but I'd also like to register a request for access to the common components. Specifically I am looking for access to the `Alpha` component in isolation. My need is slightly different than @hhedger-ae in that I don't want to reconstruct a whole picker but I want to place just the alpha slider on the page. I appreciate that I could build my own but as you know, even seemingly simple components like the alpha slider come with various hidden complexities, especially when taking a11y concerns into account, as you've already done.

**Comment by omgovich** [comment]
Hey @sanbornhilland. In your case, it seems more reasonable to just use any open-source React slider like [react-range](https://www.npmjs.com/package/react-range) and customize its style.

The reason why I suggest that is that rarge-slider-first solutions have more customizations (step size, limits, precision, different kind of callbacks). Mine components don't have any of that since they are created to use them inside `react-colorful` only. If I'll try to make the internal components more flexible it will damage the package size.
