### ISSUE TITLE
Picker does not take focus on click

### ISSUE THREAD

**Issue by felixguertler** [omgovich/react-colorful#142]
Hi there, love this project and just wanted to report on a bug.

Expected behaviour: when clicking any of the picker elements (saturation, hue, alpha) they should take focus just like they do when navigating with the `tab` key. 

Actual behaviour: clicking on the saturation, hue, alpha areas does not take focus. That means the UI does not show the same focussed state as when navigating through them via tab. This also means that they don't take away focus from other input elements.

This also happens when clicking between elements of the picker. If saturation is focused, and I adjust hue, then saturation remains focussed.

This is version 5.2.2

https://user-images.githubusercontent.com/2972170/120547881-88150b00-c3a6-11eb-8fa3-a909d73fdf47.mp4

**Comment by omgovich** [comment]
Hi! Thanks for the kind words and for so well-detailed issue.

I guess that's because we do `event.preventDefault()` in the `mousedown` handler to avoid text selection on drag.

I'll think about possible solutions.
Unfortunately, I'm getting married in 3 days, so I doubt I can fix it fast. Hope that's not super urgent for you.

**Comment by omgovich** [comment]
Hi! I just shipped v5.2.3 with the fix included. Sorry for the delay! I came back from the honeymoon 4 days ago and it took some time to get back to my open-source projects :)
