### ISSUE TITLE
Handle dragging not working inside of Panel

### ISSUE THREAD

**Issue by Noodle-Bug** [omgovich/react-colorful#167]
Clicking and dragging of the color picker handle does not work while the component is in a [FluentUI Panel.](https://developer.microsoft.com/en-us/fluentui#/controls/web/panel)
Handle goes back to working after moving the color picker outside of the panel .

![testping](https://user-images.githubusercontent.com/63314982/145147589-65cbc16c-8af0-49aa-a13e-a09c14c42854.gif)

**Comment by omgovich** [comment]
Hi! Thanks for the issue.
Not sure I understand what is "Panel". Could you create a demo (using codesanbox for example)?

**Comment by Noodle-Bug** [comment]
Sorry, I totally forgot to mention that it's a [FluentUI Panel](https://developer.microsoft.com/en-us/fluentui#/controls/web/panel)

Here is a codesandbox demonstrating the issue: https://codesandbox.io/s/modern-mountain-570fu?file=/src/App.js

**Comment by omgovich** [comment]
I don't know how, but Fluent's `Panel` component completely breaks dragging events handling.

That's definitely not `react-colorful` issue, since FluentUI breaks any component that has similar behavior.

For example, I added `react-color` and `rc-slider` to your example: these libraries don't work as well.
But if you put them outside of `<Panel>` everything is great.
https://codesandbox.io/s/admiring-waterfall-xx0kl?file=/src/App.js

**Comment by Noodle-Bug** [comment]
I did notice react-color's handle also breaks inside of the Panel as well. What's strange to me, is [Fluent UI's own Slider control](https://developer.microsoft.com/en-us/fluentui#/controls/web/slider) works inside the panel just fine:

https://codesandbox.io/s/red-paper-5cyzv?file=/src/App.js

Not sure what's going on there.
