### ISSUE TITLE
className prop is overridden by default styles

### ISSUE THREAD

**Issue by rolule** [omgovich/react-colorful#168]
Hi, 
it seems that when I pass a className prop to the HexColorPicker, this className is added to the pickers classes, but in some cases overridden by the `react-colorful` class:

When I declare this css class:
```css
.custom-picker-styles {
  width: 100%;
  height: 100%;
}
```

and add it to the picker:

```jsx
<HexColorPicker className="custom-picker-styles" />
```

the resulting Element has these classes: 
```html
<div class="react-colorful custom-picker-styles">...</div>
```

However, the width and height of the `react-colorful` class (200px) seem to override the custom values (100%). Temporary fix would be, to make width and height `!important`, but I do not think this is a good solution. I don't know if I am missing something or this is intentional. Thanks in advance :)

**Comment by omgovich** [comment]
Hi! That's a drawback of the way react-colorful injects its styles. The library adds `<style>` at the end of your website `<head>`. That means that the styles are placed after your own and in order to override them you need more specificity for your selectors.

```
<div className="my-picker">
  <HexColorPicker />
</div>

.my-picker .react-colorful {
  width: 100%;
  height: 100%;
}
.my-picker .react-colorful__alpha {
  height: 20px;
}
```

Check "Customization" section in the docs:
https://github.com/omgovich/react-colorful#customization
