### ISSUE TITLE
Add refs

### ISSUE THREAD

**Issue by atomcorp** [omgovich/react-colorful#60]
Hello, nice work on the library :)

Looks to me like I can't get a ref to the HexColorInput as things stand. From a cursory investigation you would need to implement [forwarding refs ](https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components).

The reason I would like this, is so I can focus the input by clicking on a separate DOM element. You have a really nice behaviour while staying focused and interacting with the picker, so it would be good to exploit it.

Let me know if I've missed some obvious alternative or if it would be something you'd consider adding. 

Thanks!

**Comment by omgovich** [comment]
Hi @atomcorp! Nice catch. You're right, we should forward a ref to the input node. Will do it this week.

**Comment by omgovich** [comment]
Unfortunately using `forwardRef` makes the component un-tree-shakeable. That affects the bundle size for those who use the picker only. Seems like Babel already solved this problem, but **microbundle** (which we use to build this package) doesn't support these updates yet.

I've created an issue in microbundle's repo about that:
https://github.com/developit/microbundle/issues/730

**Comment by atomcorp** [comment]
Yeah I saw the New JSX Transform announcement and thought of this!

I just ended up using my own input, so not a big problem for me now. Thanks for looking into it though.

**Comment by omgovich** [comment]
I'll close the issue then, but I'll my eye on this thing and implement refs as soon as microbundle fixes the tree shaking.

**Comment by marko-hologram** [comment]
Hey @omgovich, sorry to "resurrect" this closed issue, but I noticed that the **microbundle** issue you mentioned is closed now. Does that mean that refs can be implemented in this package or are there some blockers still present?

**Comment by omgovich** [comment]
Hi! I'll check how refs work with the new microbundle.
If it no longer breaks tree-shaking I'll prepare a new release.

**Comment by marko-hologram** [comment]
> 
> 
> Hi! I'll check how refs work with the new microbundle.
> If it no longer breaks tree-shaking I'll prepare a new release.

OMG thank you for the quickest response ever. This was so fast it felt like I contacted you on Slack or something 😄

**Comment by omgovich** [comment]
It still breaks the tree-shaking :(
Really weird: I checked microbundle's repo — the tool has Terser configured to preserve PURE annotations and @babel/plugin-transform-react-pure-annotations installed. So everything should work well, but for some reason it doesn't — after bundling there are no annotations in the compiled JS files. Probably there is a conflict between the tools microbundle uses inside.

Actually, while I was working on the experiment I realized that adding refs makes the library significantly heavier and the code became kinda ugly because of many `React.forwardRef` wrappers.

Since react-colorful is a micro-library I think it's okay if it doesn't provide this small thing.
I would recommend just wrapping the picker into a regular `div` and use it as a ref container.

**Comment by Zn4rK** [comment]
Could this be revisited? It currently leads to some quite awkward type juggling to use it as an input field for third party components (such as MUI).

If not with `forwardRef`, maybe with another prop such as `inputRef`? Then it would be possible to write a small wrapper that just forwards the ref to that input.

If that's not an option, it would be nice to get the validators and escape utils that the input field uses, so we can duplicate the logic.
