### ISSUE TITLE
Can you add onRelease event?

### ISSUE THREAD

**Issue by tombohub** [omgovich/react-colorful#75]
Hello,
onChange is nice, but in this case I am creating color palette on every color change while the color pointer is being dragged. Doesn't look smooth being dragged. If I can trigger to create palette only on release that would be nice.

Thanks

**Comment by omgovich** [comment]
Hi @tombohub.

This case is the one we know about but aren't going to implement.
Since `react-colorful` is a micro-library, we provide a color picker functionality only and try to avoid things that developers could easily implement on their side.

I would recommend you to use something like [use-debouncy](https://github.com/eavam/use-debouncy) to reduce the number of updates.

```js
import React, { useState } from 'react';
import useDebouncy from 'use-debouncy';
import { HexColorPicker } from "react-colorful";
import "react-colorful/dist/index.css";

const YourComponent = ({ color, onChange }) => {
  const [value, setValue] = useState(color);

  useDebouncy(
    () => onChange(value),
    500,
    [value],
  );

  return <HexColorPicker color={value} onChange={setValue} />;
};
```

I'm thinking about adding "Recipes" section in README to avoid similar questions.

**Comment by omgovich** [comment]
@tombohub Live example: https://codesandbox.io/s/react-colorful-debounce-dgqn0

**Comment by tombohub** [comment]
@omgovich  Ok, thats good too, thank you!
