### ISSUE TITLE
Select color doesnt works after input sequencial characteres

### ISSUE THREAD

**Issue by alpaula** [omgovich/react-colorful#92]
When used characters sequential (ffffff or cdcdcd) for input it is impossible to select another color.

**Comment by omgovich** [comment]
Hi @alpaula! Could I ask you to provide a code example or live demo on codesandbox?

**Comment by alpaula** [comment]
sorry!

https://www.loom.com/share/3ab2409798674f16b1ae1b530ee45f39

I just need the "colorful__hue", when used repeated sequencial by the input it is not possible to select the color per click.

https://codesandbox.io/s/react-colorful-hex-input-demo-forked-3tsmz?file=/src/App.js

**Comment by omgovich** [comment]
Colors like `ffffff` or `cdcdcd` are grayscale, so the behavior the picker in your demo is kinda correct.
When you type grayscale color and then change hue — it shouldn't change the color because grayscale color with other hue is the same color.

For example, white with a "red" hue is the same as white with a "blue" hue. Same for any grayscale color.

What task you are trying to solve? I'm not sure that you choose the right approach, but I can try to help you.

**Comment by alpaula** [comment]
My doubt is because the onchange is not triggered by click after the input receives strings such as "000000", "111111", "222222", "212121", "919191", for example.
In the demo I only tested "ffffff" and "000000", but any repeated sequence breaks the click.

**Comment by omgovich** [comment]
It doesn't trigger because a clicked color is the same.
When you type `919191` and then change hue the new color is also `919191` because, as I said before, changing the hue of grayscale color doesn't change color.

**Comment by omgovich** [comment]
Could you explain your task in general?

**Comment by alpaula** [comment]
I using to change items like postits and connectors in my application. The user can to choose pre-defined colors or type any.

**Comment by omgovich** [comment]
If you allow users to type any color, you should provide the full color picker functionality for them.
Why have you made the saturation area hidden?
